version: '3.8'

services:
  ai-doc-processor:
    build: .
    ports:
      - "3600:3600"
    environment:
      - NODE_ENV=production
      - PORT=3600
      - LOG_LEVEL=info
    env_file:
      - .env
    volumes:
      - ./logs:/usr/src/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3600/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 