version: '3.8'

services:
  ai-doc-processor:
    build: .
    ports:
      - "3600:3600"
    environment:
      - NODE_ENV=production
      - PORT=3600
      - LOG_LEVEL=info
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3600/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 